//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material_()
        {
            this.Products_in_materials = new HashSet<Products_in_materials>();
        }
    
        public int ID { get; set; }
        public string Material { get; set; }
        public int ID_material_type { get; set; }
        public int ID_provider { get; set; }
        public double Quantity_per_package { get; set; }
        public int ID_unit_measurement { get; set; }
        public double cost { get; set; }
        public double Quantity_stock { get; set; }
    
        public virtual Material_type_ Material_type_ { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Unit_measurement Unit_measurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_in_materials> Products_in_materials { get; set; }
    }
}
