//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewTechnologiEntities : DbContext
    {
        public NewTechnologiEntities()
            : base("name=NewTechnologiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Material_> Material_ { get; set; }
        public virtual DbSet<Material_type_> Material_type_ { get; set; }
        public virtual DbSet<Partner_products_request_> Partner_products_request_ { get; set; }
        public virtual DbSet<Partners_> Partners_ { get; set; }
        public virtual DbSet<Products_> Products_ { get; set; }
        public virtual DbSet<Products_Application> Products_Application { get; set; }
        public virtual DbSet<Products_in_materials> Products_in_materials { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type_partners_> Type_partners_ { get; set; }
        public virtual DbSet<Type_products_> Type_products_ { get; set; }
        public virtual DbSet<Type_provider> Type_provider { get; set; }
        public virtual DbSet<Unit_measurement> Unit_measurement { get; set; }
    }
}
