//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners_()
        {
            this.Partner_products_request_ = new HashSet<Partner_products_request_>();
        }
    
        public int ID { get; set; }
        public string Name_partners { get; set; }
        public int ID_Type_partners { get; set; }
        public string FamilDr { get; set; }
        public string NameDr { get; set; }
        public string OtchestvoDr { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Partner_egal_address { get; set; }
        public double INN { get; set; }
        public int Rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_products_request_> Partner_products_request_ { get; set; }
        public virtual Type_partners_ Type_partners_ { get; set; }
    }
}
