//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_in_materials
    {
        public int ID { get; set; }
        public int ID_products { get; set; }
        public int ID_material { get; set; }
    
        public virtual Material_ Material_ { get; set; }
        public virtual Products_ Products_ { get; set; }
    }
}
